import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import {
  ACCOUNT_OWNERSHIP_MAP,
  USER_BACK_REFERENCES,
  type MappedTable,
} from './ownership-map.js';

/**
 * Completeness of the ownership map, checked against the schema rather than
 * against itself.
 *
 * The map declares how each table relates to a user; nothing in that
 * declaration can notice a table that was never declared. So this guard takes
 * the other side: every table the SCHEMA actually has must appear in the map,
 * in exactly one disposition. A table added later fails this until it is
 * classified as owned, transitive, anonymize, or (with a reason) excluded.
 *
 * The schema is read from the generated `database.types.ts`, which mirrors the
 * live public schema (regenerated by `bun db:sync` / `gen-types`), the same
 * artifact-as-truth move `packages/contracts/src/entity-prefixes.spec.ts`
 * makes against the migration series.
 */
const TYPES_FILE = fileURLToPath(
  new URL('./database.types.ts', import.meta.url)
);

/**
 * Table names under `public.Tables` in the generated types. They sit at exactly
 * six-space indent (`      name: {`); Row/Insert/Update/Relationships nest
 * deeper, and the sibling blocks (Views/Functions/Enums) sit at four spaces,
 * where the scan stops.
 */
const tableBlocksFromTypes = (): Array<{ name: string; body: string }> => {
  const lines = readFileSync(TYPES_FILE, 'utf8').split('\n');
  const start = lines.findIndex((l) => /^ {4}Tables: \{$/.test(l));
  if (start === -1) {
    throw new Error('Could not find `public.Tables` in database.types.ts');
  }
  const blocks: Array<{ name: string; body: string[] }> = [];
  for (const line of lines.slice(start + 1)) {
    // A four-space `Something: {` or `};` is the next sibling — Tables ended.
    if (/^ {4}(\w+: \{|\};?)$/.test(line)) {
      break;
    }
    const match = /^ {6}(\w+): \{$/.exec(line);
    if (match?.[1]) {
      blocks.push({ name: match[1], body: [] });
      continue;
    }
    blocks.at(-1)?.body.push(line);
  }
  return blocks.map((b) => ({ name: b.name, body: b.body.join('\n') }));
};

const tablesFromTypes = (): string[] =>
  tableBlocksFromTypes().map((b) => b.name);

/**
 * Foreign keys declared in the generated types, as `table.column -> referenced
 * table`. Composite keys expand to one entry per column; none exist today, but
 * silently dropping the tail of one would be the sort of hole this file exists
 * to close.
 */
const foreignKeysFromTypes = (): Array<{
  table: string;
  column: string;
  references: string;
}> => {
  const pattern =
    /columns: \[([^\]]*)\];\s*isOneToOne: (?:true|false);\s*referencedRelation: '([^']*)';/g;
  return tableBlocksFromTypes().flatMap(({ name, body }) =>
    [...body.matchAll(pattern)].flatMap((m) =>
      [...(m[1] ?? '').matchAll(/'([^']*)'/g)].map((c) => ({
        table: name,
        column: c[1] ?? '',
        references: m[2] ?? '',
      }))
    )
  );
};

describe('account ownership map vs the schema', () => {
  const schemaTables = tablesFromTypes();
  const mapped = new Set(Object.keys(ACCOUNT_OWNERSHIP_MAP));

  // Guard the guard: if the extraction broke (file moved, indentation changed),
  // `schemaTables` would be empty and every assertion below would pass over
  // nothing — the exact failure this file exists to prevent.
  it('actually reads the generated schema', () => {
    expect(schemaTables.length).toBeGreaterThan(20);
    expect(schemaTables).toContain('memories');
    expect(schemaTables).toContain('profiles');
  });

  it('declares a disposition for every public table', () => {
    const undeclared = schemaTables.filter((t) => !mapped.has(t)).sort();
    expect(undeclared).toEqual([]);
  });

  it('maps no table the schema does not have', () => {
    const schema = new Set(schemaTables);
    const stale = [...mapped].filter((t) => !schema.has(t)).sort();
    expect(stale).toEqual([]);
  });

  it('catches an undeclared table', () => {
    // Proves the check fires rather than passing vacuously: a table present in
    // the schema but absent from the map is reported.
    const map = new Set(['memories']);
    const schema = ['memories', 'a_new_table'];
    expect(schema.filter((t) => !map.has(t))).toEqual(['a_new_table']);
  });
});

/**
 * Completeness of the back-reference list, checked the same way.
 *
 * The table map answers "whose row is this"; it cannot see a column on SOMEONE
 * ELSE's row that merely names a user — who resolved a review, who granted a
 * membership. Those columns have to be severed on erasure or the final profile
 * delete aborts on them, and the list that enumerates them had no guard at all
 * until this one: `portability_candidates.resolved_by` was severed by the
 * cascade for a full release while going undeclared here, and nothing noticed.
 *
 * Scope: references to `profiles` only. For those the dichotomy is exact — a
 * user column either says the row IS that user's (the map's business) or that
 * it merely names them (this list's). References to `memories` have a third
 * case the vocabulary does not yet cover: a row that is neither owned by the
 * memory nor severed from it, but DELETED with it because it is meaningless
 * without its subject (`brief_probes.memory_id`, `roi_probes.source_memory_id`).
 * Those are left out rather than forced into a shape that does not fit.
 */
describe('user back-references vs the schema', () => {
  const foreignKeys = foreignKeysFromTypes();
  const userRefs = foreignKeys.filter((fk) => fk.references === 'profiles');
  const declared = new Set(
    USER_BACK_REFERENCES.map((r) => `${r.table}.${r.column}`)
  );

  /** The column by which the map already attributes a row to its owner. */
  const ownColumn = (table: string): string | undefined => {
    const disposition = ACCOUNT_OWNERSHIP_MAP[table as MappedTable];
    if (disposition?.kind === 'owned') {
      return disposition.ownerColumn;
    }
    if (disposition?.kind === 'anonymize') {
      return disposition.column;
    }
    return undefined;
  };

  it('actually reads the foreign keys', () => {
    expect(foreignKeys.length).toBeGreaterThan(20);
    expect(userRefs.length).toBeGreaterThan(10);
  });

  it('declares every user reference that is not an ownership column', () => {
    const undeclared = userRefs
      .filter(
        (fk) =>
          fk.column !== ownColumn(fk.table) &&
          !declared.has(`${fk.table}.${fk.column}`)
      )
      .map((fk) => `${fk.table}.${fk.column}`)
      .sort();
    expect(undeclared).toEqual([]);
  });

  it('declares no reference the schema does not have', () => {
    const columns = new Set(
      foreignKeys.map((fk) => `${fk.table}.${fk.column}`)
    );
    const stale = [...declared].filter((r) => !columns.has(r)).sort();
    expect(stale).toEqual([]);
  });
});
