import { config } from '@workspace/eslint-config/base';

/** @type {import("eslint").Linter.Config} */
export default [
  ...config,
  {
    // Generated by `supabase gen types` — do not lint.
    ignores: ['src/database.types.ts'],
  },
];
